### ISSUE TITLE
Recording of historical SSB0 (year 1 of historical period)

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/OMtool#4]
need recording the first historical SSB (ie SSB0hist) which is total SSB by simulation in year 1 of the historical time period in MSE@Ref$ReferencePoints$SSB0hist

**Comment by AdrianHordyk** [comment]
Historical spawning biomass is in `Hist@TSdata$SBiomass` (dimensions `nsim`, `nyears`, `nareas`)
